### PR TITLE
Fix privileges check

### LINKED ISSUE #107: The current privileges check is wrong
This [commit](https://github.com/servo/homu/commit/9a546084dac636cffc38a404d4b5c87f064ba649) changed the privileges check, it will cause the homu always reply a `Insufficient privileges` comment when some one that don't have any privileges make a event on the Pull Request, such as comment or push.

See the [detail](https://github.com/servo/homu/blob/9a546084dac636cffc38a404d4b5c87f064ba649/homu/main.py#L386-L401).

### PR DESCRIPTION
**Pull request by coldnight**
fixes #107

---
This change is [Reviewable](https://reviewable.io/reviews/servo/homu/108)

### CODE REVIEW

**Comment by coldnight** [comment]
@edunham @Manishearth r?

**Comment by coldnight** [comment]
@edunham @KiChjang @bors-servo ping?

**Comment by Valloric** [comment]
I'm seeing the same bug this PR is fixing; any chance this could be merged? It seems to have all the approvals...

**Comment by Valloric** [comment]
@cbrewster Thank you!

**Pull request merged**
