### PR TITLE
Add support for github checks

### PR DESCRIPTION
**Pull request by jdm**
Rebased from https://github.com/rust-ops/homu/pull/10.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/homu/186)

### CODE REVIEW

**Comment by Manishearth** [comment]
ideally we'd update the travis exemption code as well, but nbd if we don't immediately

**Comment by jdm** [comment]
Since the travis/status exemption code only works when local Git commands are used, Servo has never made use of that. I am inclined to put off making those changes until later in that case.

**Pull request merged**
