### PR TITLE
Fix travis exemption code again for status-only context

### PR DESCRIPTION
**Pull request by cgwalters**
It seems that
https://github.com/servo/homu/pull/13/commits/7fa396555de01b8dd19bd78a21c64c647926e199
regressed things when using status only.

The format seems to have changed at one point to a dictionary, but
this code was treating it as a list (using `[0]`).

Since we were already iterating over the statuses, move the special
casing for "status-only-travis" up to there, and slay the massive
conditional.

Conflicts:
	homu/main.py

---
This change is [Reviewable](https://reviewable.io/reviews/servo/homu/29)

### CODE REVIEW

**Comment by cgwalters** [comment]
NB: I tested this with a status-only config, but I didn't test travis exemption.

**Comment by Manishearth** [comment]
Ah, my bad.

**Comment by Manishearth** [comment]
Thanks!

**Pull request merged**
