### PR TITLE
Don't stop processing the queue when tree is closed

### PR DESCRIPTION
**Pull request by Manishearth**
This change is [Reviewable](https://reviewable.io/reviews/servo/homu/121)

### CODE REVIEW

**Comment by Eh2406** [comment]
Maybe I am misunderstanding. The "repo_states" are sorted, once we hit something below tree closed so will the rest of the list. Right?

**Comment by Manishearth** [comment]
Apparently this doesn't take retries into account

**Comment by Manishearth** [comment]
No, wait, you're right, retries don't work that way. Hm.

**Comment by Eh2406** [comment]
I think this may be a good place to start adding tests. We could add a function `def(queue) -> state to process` that does not have side effects. Then we can check a bunch of different `queue` to ensure they work correctly. Then maybe we can determine why this one is not working correctly.

**Comment by Manishearth** [comment]
Okay, I can't repro this failure in the first place. But I did find a bug in the hook impl (
https://github.com/servo/homu/pull/122)

**Comment by Manishearth** [comment]
See https://github.com/Manishearth/test_repo/pull/6#issuecomment-304406140

**Comment by Eh2406** [comment]
I started experimenting with creating a separate function. [diff](https://github.com/servo/homu/compare/continue...Eh2406:continue). In the first commit I just move it over. In the second commit I try and simplify the logic.

I think this new function is amenable to testing, but I have not set it up yet.

**Comment by Eh2406** [comment]
I think I know how to reproduce the original issue, and yes your pr fixes it.

1. add a pr r=try to the queue p=10 it will succeed so it will be at the top of the queue.
2. treeclose to 1000
3 add a pr r=me to the queue p=1001, this pr will not start as the old code will stop at the pr from 1. Which is higher in the sort order as it has status="success".

**Comment by Manishearth** [comment]
In that case, r? @edunham

**Comment by Manishearth** [comment]
Though, r+ after try doesn't work anyway, you need to `r+ clean` it.

**Pull request merged**
