### PR TITLE
add homu ping command (fixes #83)

### LINKED ISSUE #83: Add command to confirm that Homu is listening
There are 2 cases in which users spam retry on a PR: When it really needs to be retried, and also when they're testing whether Homu is listening at all. 

To reduce ambiguity, it would be nice to add a "@bors-servo: hello?" command, to which Homu would simply answer "@username: Hi there!" or equivalent. This way it would be clear which messages are simply debugging whether the bot is listening, vs which actually want a build to be kicked off.

### PR DESCRIPTION
**Pull request by Manishearth**
Was thinking of adding a Portal easter egg with "are you still there?" but I'm not sure if I should.

r? @edunham

---
This change is [Reviewable](https://reviewable.io/reviews/servo/homu/84)

### CODE REVIEW

**Comment by cgwalters** [comment]
LGTM.  I am also totally in favor of the Portal easter egg!

**Comment by cgwalters** [comment]
(That said I think the real fix for this is to make the web UI more useful but that's a harder topic)

**Comment by Manishearth** [comment]
Now with 100% more 🍰

**Comment by cgwalters** [comment]
🏆 Awesome!

**Pull request merged**
