### PR TITLE
Incorporate 'flake8' linting via Travis CI

### PR DESCRIPTION
**Pull request by frewsxcv**
Rebase of #107

[Review on Reviewable](https://reviewable.io/reviews/servo/homu/2)

### CODE REVIEW

**Comment by Manishearth** [comment]
I'd rather not diverge from homu/homu too much; this PR will make every uplift need merge conflict fixing.

(Also, I'd rather not switch to servo/homu unless we really need to)

**Comment by frewsxcv** [comment]
> (Also, I'd rather not switch to servo/homu unless we really need to)

Homu seems to break every day. How confident are you that your SQLite changes today fixes that?

**Comment by frewsxcv** [comment]
> (Also, I'd rather not switch to servo/homu unless we really need to)

Also, why?

**Comment by Manishearth** [comment]
> Homu seems to break every day.

AFAICT that was one bit of brokenness introduced due to homu being restarted at the wrong time, which sort of stayed around mucking up the internals and making it keep two pending PRs at all times.

How does switching to servo/homu fix it, even if it was a code issue?

I don't mind switching to get upstream patches faster, I'd rather avoid _diverging_ though.

**Comment by Manishearth** [comment]
> Also, why?

Just extra work to keep it up to date. I don't like forking unless there's a need; code formatting isn't a need :smile:

**Comment by frewsxcv** [comment]
> How does switching to servo/homu fix it, even if it was a code issue?

I was planning to maintain this repository. I wanted to start by incorporating a sane linter.

**Comment by frewsxcv** [comment]
So, a month later. Have any thoughts about this now?

**Comment by Manishearth** [comment]
Update master to homu master first, but sure, merge this!

**Comment by frewsxcv** [comment]
From what I can tell, servo/homu is up-to-date with barosl/homu, if that's what you're asking

**Comment by frewsxcv** [comment]
Also, should we get homu set up here in servo/homu? :stuck_out_tongue:

**Comment by Manishearth** [comment]
r+

**Pull request merged**
